FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements_withtorch.txt
RUN pip install -r requirements.txt

COPY . .

RUN python getmodel.py

CMD ["python", "local_detection_server.py"]